baseURL: https://main.d3sfo5wfgocqj0.amplifyapp.com
languageCode: de-de
title: "Aleksandar Tolev"
theme: "toha"

languages:
  de:
    languageName: German
    weight: 1
  en:
    languageName: English
    weight: 3
  

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg
  logo:
    main: /images/site/logo.png
    inverted: /images/site/logo.png
    favicon: /images/site/favicon.png
  enableBlogPost: false
  enableTOC: true
  newsletter:
    enable: false
  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true

deployment:
  targets:
    name: "homepageDeployment"
    URL: "s3://homepage-aleks?region=eu-central-1"
