baseURL: https://tolev.de
languageCode: de-de
title: "Aleksandar Tolev"
theme: "toha"

languages:
  de:
    languageName: German
    weight: 1
  en:
    languageName: English
    weight: 3
  

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

params:
  background: images/author/atolev.png
  logo:
    main: images/author/logo.png
    inverted: images/author/logo.png
    favicon: images/author/favicon.png
  enableBlogPost: false
  enableTOC: true
  newsletter:
    enable: false
  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true


